### PR TITLE
fixed nav to home and made nav more readable

### PR DESCRIPTION
**Pull request by nadav-ab**
fix navigation to home

make nav more readable

### CODE REVIEW

**Review by idoros — APPROVED** [review]

**Comment by noammu** [comment]
Validated 👍

**Comment by noammu** [comment]
Closes: https://github.com/wixplosives/codux/issues/23364

**Comment by idoros** [comment]
I see what it fixes now, test?

**Comment by noammu** [comment]
Nadav will talk with you about the tests but he wants to merge it now

**Pull request merged**
